name: currency_test
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Provider
  provider: ^6.0.5

  #Rout
  go_router: ^6.5.7

  #.env
  flutter_dotenv: ^5.1.0

  #Network
  http: ^0.13.6

  #UI
  google_fonts: ^4.0.4
  cron: ^0.5.1

  #LocalStorage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.10 # flutter packages pub run build_runner build
  hive_generator: ^1.1.2

flutter:
  uses-material-design: true

  assets:
    - .env.dev
    - .env.prod
